import http from 'node:http';import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';import {accountURL,parseFeed,parseTrends,meta,strip} from './strategy.mjs';
const root=path.dirname(fileURLToPath(import.meta.url)),feedURL='https://trends.google.com/trending/rss?geo=KR',mime={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8','.mjs':'text/javascript; charset=utf-8','.woff2':'font/woff2','.png':'image/png','.jpg':'image/jpeg','.json':'application/json; charset=utf-8'};let trendCache=null;
const historyDir=path.join(root,'runtime');fs.mkdirSync(historyDir,{recursive:true});const historyPath=path.join(historyDir,'keyword-history.json');let history=[];try{history=JSON.parse(fs.readFileSync(historyPath,'utf8'));}catch{}
const koreaDay=t=>new Date(new Date(t).getTime()+9*3600000).toISOString().slice(0,10);
function remember(feed){const day=koreaDay(feed.fetchedAt);const old=history.find(x=>x.day===day);if(old){const map=new Map(old.items.map(x=>[x.title,x]));for(const x of feed.items)map.set(x.title,x);old.items=[...map.values()];old.fetchedAt=feed.fetchedAt;}else history.push({day,fetchedAt:feed.fetchedAt,items:feed.items});history=history.filter(x=>Date.now()-Date.parse(x.day)<15*86400000);fs.writeFileSync(historyPath,JSON.stringify(history,null,2));}
function keywordHistory(){const today=koreaDay(new Date()),base=new Date(today+'T00:00:00Z'),dow=(base.getUTCDay()+6)%7,weekStart=new Date(+base-dow*86400000).toISOString().slice(0,10);return {today,weekStart,days:history.filter(x=>x.day>=weekStart&&x.day<=today)};}

const allowed=h=>['www.instagram.com','instagram.com','blog.naver.com','m.blog.naver.com','rss.blog.naver.com','brunch.co.kr','trends.google.com','www.youtube.com','youtube.com','www.tiktok.com','tiktok.com','x.com','twitter.com','threads.net','www.threads.net','threads.com','www.threads.com','www.facebook.com','facebook.com','www.linkedin.com','linkedin.com','www.pinterest.com','pinterest.com'].includes(h)||/^[a-z0-9-]+\.tistory\.com$/.test(h);
async function read(url,depth=0){const u=new URL(url);if(u.protocol!=='https:'||u.username||u.password||u.port||!allowed(u.hostname)||depth>3)throw Error('이 공개 주소는 읽을 수 없습니다.');const r=await fetch(u,{redirect:'manual',signal:AbortSignal.timeout(12000),headers:{'User-Agent':'ColorfulPictureLife/0.8 (public-page-reader)','Accept':'text/html,application/rss+xml,application/xml,text/xml'}});if(r.status>=300&&r.status<400){const next=new URL(r.headers.get('location'),u);return read(next.href,depth+1);}if(!r.ok)throw Error(`공개 자료 접근 응답 ${r.status}`);const type=r.headers.get('content-type')||'';if(!/html|xml|text/.test(type))throw Error('읽을 수 있는 공개 문서가 아닙니다.');let size=0,text='';const reader=r.body.getReader(),decoder=new TextDecoder();for(;;){const {value,done}=await reader.read();if(done)break;size+=value.length;if(size>2000000){await reader.cancel();throw Error('공개 문서 크기가 읽기 범위를 넘었습니다.');}text+=decoder.decode(value,{stream:true});}return text+decoder.decode();}
const json=(res,status,obj)=>{res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'});res.end(JSON.stringify(obj));};
http.createServer(async(req,res)=>{try{const host=(req.headers.host||'').split(':')[0];if(!['127.0.0.1','localhost'].includes(host))return json(res,403,{error:'내 컴퓨터에서만 사용할 수 있습니다.'});if(req.headers.origin&&new URL(req.headers.origin).host!==req.headers.host)return json(res,403,{error:'다른 페이지의 요청은 허용하지 않습니다.'});const u=new URL(req.url,'http://localhost');
 if(u.pathname==='/api/trends'&&req.method==='GET'){if(trendCache&&Date.now()-Date.parse(trendCache.fetchedAt)<300000)return json(res,200,{...trendCache,history:keywordHistory()});const xml=await read(feedURL);const next={source:feedURL,fetchedAt:new Date().toISOString(),kind:'한국 Google 검색 관심 신호 ,  SNS 바이럴 미확인',items:parseTrends(xml)};trendCache=next;remember(next);return json(res,200,{...next,history:keywordHistory()});}
 if(u.pathname==='/api/account'&&req.method==='POST'){let body='';for await(const chunk of req){body+=chunk;if(Buffer.byteLength(body)>4000)return json(res,413,{error:'주소 입력을 확인해 주세요.'});}const a=accountURL(JSON.parse(body).url),result={...a,checkedAt:new Date().toISOString(),title:'',description:'',posts:[],status:'unavailable',limitation:'공개 문서 접근이 제한됐습니다. 비공개 정보, 도달, 공유, 저장 수는 읽지 않습니다.'};try{const html=await read(a.feed||a.url);if(a.feed){result.posts=parseFeed(html);result.title=strip(html.match(/<channel>[\s\S]*?<title>([\s\S]*?)<\/title>/)?.[1]||'');result.description=strip(html.match(/<channel>[\s\S]*?<description>([\s\S]*?)<\/description>/)?.[1]||'');result.status=result.posts.length?'public-posts':'limited';result.limitation='RSS에 제공된 최근 글 제목, 날짜, 본문 일부입니다. 전체 기록이나 읽은 사람, 공유 통계는 아닙니다.';}else{result.title=meta(html,'og:title');result.description=meta(html,'og:description')||meta(html,'description');if(/로그인|log in|sign up/i.test(result.description+result.title)&&!result.title.includes(a.id)){result.title='';result.description='';}result.status=result.description?'public-profile':'limited';result.limitation='공개 페이지 소개만 읽었습니다. 사진의 색, 게시물 내용, 반응은 자동 평가하지 않았습니다.';}}catch(e){result.reason=e.message;}return json(res,200,result);}
 if(u.pathname.startsWith('/api/'))return json(res,404,{error:'지원하지 않는 요청입니다.'});const rel=decodeURIComponent(u.pathname).slice(1)||'index.html',file=path.resolve(root,rel);if(!file.startsWith(root+path.sep)||rel==='server.mjs'||rel.split('/').includes('runtime')||rel.includes('test')||!mime[path.extname(file)]||!fs.existsSync(file)||!fs.statSync(file).isFile())return json(res,404,{error:'파일 없음'});res.writeHead(200,{'Content-Type':mime[path.extname(file)],'X-Content-Type-Options':'nosniff','Cache-Control':'no-store'});fs.createReadStream(file).pipe(res);
 }catch(e){json(res,400,{error:e.message||'자료를 읽지 못했습니다.'});}}).listen(4191,'127.0.0.1',()=>console.log('http://127.0.0.1:4191/'));
