export const decode=s=>String(s||'').replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,'$1').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;|&apos;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&#(x[0-9a-f]+|[0-9]+);/gi,(_,n)=>{const value=n[0].toLowerCase()==='x'?parseInt(n.slice(1),16):Number(n);return value<=0x10ffff?String.fromCodePoint(value):'';});
export const strip=s=>decode(s).replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim();
export const tag=(s,n)=>decode(s.match(new RegExp('<'+n+'(?:\\s[^>]*)?>([\\s\\S]*?)</'+n+'>','i'))?.[1]||'').trim();
export function accountURL(raw){let u;try{u=new URL(raw.trim().startsWith('https://')?raw.trim():'https://'+raw.trim());}catch{throw Error('SNS 주소를 확인해 주세요.');}if(u.protocol!=='https:'||u.port||u.username||u.password)throw Error('https SNS 주소만 사용할 수 있습니다.');const parts=u.pathname.split('/').filter(Boolean);let platform,id;
 if(['instagram.com','www.instagram.com'].includes(u.hostname)){platform='Instagram';id=parts[0];if(parts.length!==1||['p','reel','accounts','explore','stories'].includes(id))throw Error('게시물 대신 Instagram 프로필 주소를 넣어 주세요.');}
 else if(['blog.naver.com','m.blog.naver.com'].includes(u.hostname)){platform='네이버 블로그';id=parts[0];if(parts.length!==1)throw Error('블로그 홈 주소를 넣어 주세요.');}
 else if(/^[a-z0-9-]+\.tistory\.com$/.test(u.hostname)){platform='티스토리';id=u.hostname.split('.')[0];if(parts.length)throw Error('블로그 홈 주소를 넣어 주세요.');}
 else if(u.hostname==='brunch.co.kr'&&parts.length===1&&parts[0].startsWith('@')){platform='브런치';id=parts[0].slice(1);}
 else {const names={'youtube.com':'YouTube','www.youtube.com':'YouTube','youtu.be':'YouTube','www.tiktok.com':'TikTok','tiktok.com':'TikTok','x.com':'X','twitter.com':'X','www.threads.net':'Threads','threads.net':'Threads','www.threads.com':'Threads','threads.com':'Threads','www.facebook.com':'Facebook','facebook.com':'Facebook','www.linkedin.com':'LinkedIn','linkedin.com':'LinkedIn','www.pinterest.com':'Pinterest','pinterest.com':'Pinterest'};if(!u.hostname.includes('.')||/^\d[\d.]*$/.test(u.hostname)||u.hostname==='localhost'||u.hostname.endsWith('.local'))throw Error('공개 SNS 주소를 넣어 주세요.');return {platform:names[u.hostname]||'기타 SNS',id:u.hostname+u.pathname,url:u.origin+u.pathname,feed:null};}
 if(!id||!/^[-a-zA-Z0-9_.]+$/.test(id))throw Error('계정 이름을 확인해 주세요.');
 const url=platform==='Instagram'?`https://www.instagram.com/${id}/`:platform==='네이버 블로그'?`https://blog.naver.com/${id}`:platform==='티스토리'?`https://${id}.tistory.com/`:`https://brunch.co.kr/@${id}`;
 return {platform,id,url,feed:platform==='네이버 블로그'?`https://rss.blog.naver.com/${id}.xml`:platform==='티스토리'?`https://${id}.tistory.com/rss`:null};
}
export function parseFeed(xml){return [...xml.matchAll(/<item(?:\s[^>]*)?>([\s\S]*?)<\/item>/g)].slice(0,25).map(m=>({title:strip(tag(m[1],'title')),url:tag(m[1],'link'),date:tag(m[1],'pubDate'),description:strip(tag(m[1],'description')).slice(0,500)}));}
export function parseTrends(xml,now=new Date()){return [...xml.matchAll(/<item(?:\s[^>]*)?>([\s\S]*?)<\/item>/g)].slice(0,30).map(m=>{const x=m[1],date=tag(x,'pubDate'),time=Date.parse(date);return {title:strip(tag(x,'title')),traffic:tag(x,'ht:approx_traffic'),date,ageHours:Number.isFinite(time)?Math.round((+now-time)/3600000):null,news:[...x.matchAll(/<ht:news_item>([\s\S]*?)<\/ht:news_item>/g)].slice(0,2).map(n=>({title:strip(tag(n[1],'ht:news_item_title')),url:tag(n[1],'ht:news_item_url'),publisher:tag(n[1],'ht:news_item_source')}))};}).filter(x=>x.title&&x.ageHours!==null&&x.ageHours>=0&&x.ageHours<=168);}
export function meta(html,name){for(const m of html.matchAll(/<meta\b[^>]*>/gi)){const n=m[0].match(/(?:name|property)\s*=\s*["']([^"']+)/i)?.[1],v=m[0].match(/content\s*=\s*["']([^"']*)/i)?.[1];if(n===name)return strip(v);}return '';}
export function recommend(account,topic,goal){const photo=/사진|색감|촬영|풍경/.test(topic),ig=account.platform==='Instagram';const confirmed=account.posts?.length>0;const items=[
 {title:'처음 보는 사람이 이해할 한 문장',state:account.description?'공개 페이지 설명 확인 ,  소개 문구 별도 검토':'소개 확인 필요',why:account.description||'프로필 소개를 읽지 못했습니다. 계정의 대상을 추정하지 않습니다.',action:photo?'“일상에서 지나친 색을 발견하는 사진 기록”처럼 대상과 차별점을 소개하고, 대표 게시물에도 같은 약속을 연결하세요.':`“${topic||'내 주제'}를 누구에게 어떤 관점으로 전하는지” 한 문장으로 정리하세요.`},
 {title:ig?'첫 장면과 공유할 이유':'제목과 읽을 이유',state:'콘텐츠 제안',why:confirmed?`최근 공개 글 ${account.posts.length}개를 읽었습니다. 제목, 본문 일부는 확인했지만 공유 효과는 측정하지 않았습니다.`:'개별 콘텐츠를 읽지 못해 플랫폼과 직접 입력한 주제를 바탕으로 제안합니다.',action:ig?(photo?'사진의 색과 전체 구도를 바로 보여주고 “이 색을 보면 떠오르는 사람은?”처럼 보낼 상대가 떠오르는 질문을 시험하세요.':'결과나 상황을 첫 장면에서 보여주고, 독자가 친구에게 보낼 만한 구체적인 이유를 붙이세요.'):'제목에 독자의 상황과 얻을 내용을 담고, 본문에서 답, 직접 경험, 근거를 제공하세요. 현재 제목을 평가하려면 아래 읽은 글을 확인하세요.'},
 {title:'형식, 게시 주기, 키워드 조건',state:'초기 검토안 ,  계정 성과 미검증',why:'정답인 게시 횟수나 해시태그 수를 계정 주소만으로 계산할 수는 없습니다.',action:ig?'확산 목적 릴스와 저장 목적 캐러셀을 역할별로 제안합니다. 제작 가능한 횟수를 정하고 같은 관측 기간으로 비교하세요. 주제, 장소, 대상과 직접 관련된 키워드만 사용하고 무관한 인기 태그는 제외하세요.':'최근 글에서 반복되는 주제를 묶어 연재를 구성하고 관련 글을 연결하세요. 독자가 실제로 찾을 표현을 제목, 본문에 자연스럽게 사용하세요.'},
 {title:'트렌드와 브랜드의 연결',state:'적합성 검토',why:`입력 목표: ${goal}. 최신 검색 관심 신호를 그대로 따라가는 대신 주제 연관성을 확인합니다.`,action:photo?'문화, 전시, 공간, 계절 신호 중 실제 촬영하거나 설명할 수 있는 소재를 고르세요. 경제 뉴스가 급상승해도 사진 브랜드와 관련이 없으면 제외하세요.':`아래 후보 중 ${topic||'내 브랜드'}의 경험과 연결할 수 있는 것을 선택하고, 사실 확인 → 브랜드 관점 → 참여 질문 순서로 구성하세요.`},
 {title:'많이 본 뒤 무엇을 기억할지',state:'측정 자료 필요',why:'좋아요, 조회수만으로 브랜드 기억이나 재방문을 증명하지 않습니다.',action:'“이 계정을 한 문장으로 소개한다면?”의 실제 응답이나 댓글의 브랜드 표현을 확인하세요. 반복 참여 자료가 있을 때만 다시 찾는 반응을 비교하고 다음 편의 약속을 조정하세요.'},
 {title:'추천에 노출될 기본 조건',state:ig?'공식 안내 참고 ,  계정 상태 미확인':'원본 경험, 출처 확인',why:ig?'Meta는 2024 공식 안내에서 원본 콘텐츠와 추천 자격을 설명했습니다. 현재 계정의 추천 자격은 이 서비스에서 읽지 못합니다.':'외부 글 요약만으로 차별점을 확보했다고 판단하지 않습니다.',action:ig?'직접 만든 콘텐츠인지, 다른 앱의 워터마크가 있는지 확인하고 계정 내 추천 자격을 점검하세요. 추천 자격을 갖춰도 확산이 보장되는 것은 아닙니다.':'본인의 사진, 경험, 근거를 드러내고, 참고 자료의 출처와 자신의 해석을 구분하세요.'}
];if(['YouTube','TikTok'].includes(account.platform)){items[1].title='영상의 첫 장면과 공유할 이유';items[1].action='영상에서 얻을 결과나 생활 상황을 시작 부분에 드러내고, 직접 만든 장면과 친구에게 보낼 이유를 연결하세요. 실제 시청 유지, 공유 자료 없이 현재 영상의 성과를 판정하지 않습니다.';items[2].action='발견용 짧은 영상과 설명을 이어가는 영상의 역할을 나누고 제작 가능한 주기를 정하세요. 관련 주제를 제목과 설명에 일관되게 연결하세요. 게시 횟수의 정답을 보장하지 않습니다.';}return items;}
