const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const today=()=>new Date(Date.now()+9*3600000).toISOString().slice(0,10),key='perjim-source-observations-v13';
export const providers={
 naver:{name:'네이버 데이터랩',group:'검색',url:'https://datalab.naver.com/keyword/trendSearch.naver',unit:'검색 상대 지수',description:'같은 조회 결과에서 최대 검색 관심을 100으로 둔 상대값. 검색 횟수가 아닙니다.',status:'원문 조회, 수치 기록 지원. 인증값 미설정으로 자동 조회 미연결.'},
 google:{name:'Google Trends',group:'검색',url:'https://trends.google.co.kr/trends/',unit:'검색 관심',description:'최신 한국 급상승 검색 관심을 피드로 읽습니다. 탐색 화면의 상대 지수와 피드 검색량은 구분합니다.',status:'한국 급상승 피드 자동 조회'},
 bigkinds:{name:'빅카인즈',group:'뉴스',url:'https://www.bigkinds.or.kr/',unit:'기사 건수',description:'검색어가 포함된 뉴스의 기간별 기사 건수를 확인합니다. 사람 수나 공유 수가 아닙니다.',status:'원문 조회, 수치 기록 지원. 자동 기사 수집 미연결.'},
 some:{name:'썸트렌드',group:'소셜',url:'https://some.co.kr/analysis/compare/mention',unit:'언급량',description:'단어가 언급된 자료의 수를 기간, 채널과 함께 확인합니다. 채널과 이용 범위는 원문에서 확인하세요.',status:'원문 조회, 수치 기록 지원. 자동 소셜 수집 미연결.'},
 words:{name:'트렌드어워드',group:'신조어, 문화',url:'https://maily.so/trendaword/posts',unit:'뉴스레터 조회 표시',description:'신조어, 밈의 사용 맥락을 읽습니다. 레터 조회는 SNS 시장 전체 언급량이 아닙니다.',status:'공개 레터 확인본, 자동 갱신 아님.'}
};
let records=[];try{const r=JSON.parse(localStorage.getItem(key)||'[]');if(Array.isArray(r))records=r;}catch{}
const letters=[
 {keyword:'젠모지',date:'2026-10-06',views:'4.21K',url:'https://maily.so/trendaword/posts/10z373lvolw',hint:'개인 표현과 조합 놀이의 맥락을 확인하고, 브랜드 고유의 소재로 연결할 수 있는지 검토하세요.'},
 {keyword:'AI 한 단어 대답',date:'2026-10-01',views:'5.25K',url:'https://maily.so/trendaword/posts/mjz6v2pnowk',hint:'짧은 질문과 답의 참여 형식을 검토하세요. 광고가 포함된 레터입니다.'},
 {keyword:'빙하기 밈',date:'2026-09-23',views:'6.56K',url:'https://maily.so/trendaword/posts/e9o036m4o8w',hint:'계절의 변화를 함께 경험하는 맥락을 확인하세요. 과거 발행 자료이며 현재 유행으로 확정하지 않습니다.'}
];
const checkedAt='2026-10-07T14:28:52.660294+00:00';
function inPeriod(start,end){const t=today();if($('period').value==='today')return start<=t&&end>=t;const d=new Date(t+'T00:00:00Z'),n=(d.getUTCDay()+6)%7,m=new Date(+d-n*86400000).toISOString().slice(0,10);return end>=m&&start<=t;}
export function renderSource(kind){const p=providers[kind],word=$('keyword').value.trim();if(kind==='words'){
 const rows=letters.filter(r=>inPeriod(r.date,r.date)&&(!word||r.keyword.includes(word)));
 $('trend-status').textContent=`트렌드어워드 공개 확인본 ${rows.length}건, 확인 ${new Date(checkedAt).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'})}, 발행일 기준 필터. 자동 갱신 아님. 조회수는 레터 조회 표시이며 SNS 언급량이 아닙니다.`;
 $('trend-list').innerHTML=rows.length?rows.map(r=>`<article class="panel trend-card"><span class="tag">신조어, 문화, 공개 레터</span><h3>${esc(r.keyword)}</h3><dl class="trend-metrics"><div><dt>레터 조회 표시</dt><dd>${r.views}</dd></div><div><dt>발행일</dt><dd class="metric-date">${r.date}</dd></div></dl><p>${esc(r.hint)}</p><details class="evidence-details"><summary>근거 보기, 레터와 출처</summary><p><a href="${r.url}" target="_blank" rel="noopener">용례와 사용 맥락 읽기</a></p><p>공개 페이지 표시값을 확인했습니다. 고유 독자, 공유, 증가율은 확인하지 못했습니다.</p></details><button data-research="${esc(r.keyword)}">콘텐츠 방향 검토</button></article>`).join(''):`<article class="panel"><h3>현재 기간에 확인한 레터가 없습니다</h3><p>이번 주로 바꾸거나 원문에서 최신 발행을 확인하세요. 확인본 밖의 내용을 만들어 표시하지 않습니다.</p><a href="${p.url}" target="_blank" rel="noopener">트렌드어워드 원문</a></article>`;return;
 }
 const rows=records.filter(r=>r.provider===kind&&inPeriod(r.start,r.end)&&(!word||r.keyword.includes(word)));
 $('trend-status').textContent=`${p.name} 확인 수치 ${rows.length}건, ${p.status}, 기간과 조회 조건이 다른 수치를 합산하지 않습니다.`;
 $('trend-list').innerHTML=rows.length?rows.map(r=>`<article class="panel trend-card"><span class="tag">${p.name}, 직접 확인 기록</span><h3>${esc(r.keyword)}</h3><dl class="trend-metrics"><div><dt>${p.unit}</dt><dd>${Number(r.value).toLocaleString()}</dd></div></dl><p>${r.start} ~ ${r.end}</p><p class="source">${esc(r.scope)}</p><details class="evidence-details"><summary>근거 보기, 조건과 출처</summary><p>${p.description}</p><p>확인 ${new Date(r.checkedAt).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'})}, 입력값 자동 검증 안 됨</p><a href="${esc(r.url)}" target="_blank" rel="noopener">확인 원문</a></details><button data-research="${esc(r.keyword)}">콘텐츠 방향 검토</button></article>`).join(''):`<article class="panel"><h3>${p.name} 수치를 확인해 주세요</h3><p>${p.description}</p><p>아직 확인한 수치가 없습니다. 아래 원문에서 조회한 뒤 ‘외부 사이트의 수치 기록’에 기간, 조건과 함께 저장하면 이 화면에 표시됩니다.</p><a href="${p.url}" target="_blank" rel="noopener">${p.name}에서 확인</a></article>`;
}
export function setupSources(){
 $('source-links').innerHTML=Object.entries(providers).map(([id,p])=>`<article class="source-tile"><span class="tag">${p.group}</span><h4>${p.name}</h4><p>${p.description}</p><small>${p.status}</small><p><a href="${p.url}" target="_blank" rel="noopener">원문 열기</a>, <button type="button" data-provider="${id}">자료 보기</button></p></article>`).join('');
 $('source-links').addEventListener('click',e=>{const b=e.target.closest('[data-provider]');if(!b)return;const kind=b.dataset.provider==='google'?'search':b.dataset.provider;$('kind').value=kind;if(kind==='search')$('kind').dispatchEvent(new Event('input'));else renderSource(kind);$('trends').scrollIntoView({block:'start',behavior:'smooth'});});
 const updateUnit=()=>{$('source-unit').textContent=providers[$('source-provider').value].description;};$('source-provider').onchange=updateUnit;updateUnit();$('source-start').value=today();$('source-end').value=today();
 $('source-form').onsubmit=e=>{e.preventDefault();try{const provider=$('source-provider').value,keyword=$('source-word').value.trim(),value=Number($('source-value').value),start=$('source-start').value,end=$('source-end').value,scope=$('source-scope').value.trim(),u=new URL($('source-url').value),p=providers[provider];if(!keyword||!scope||!start||!end||start>end||end>today())throw Error('키워드, 조건, 날짜를 확인하세요. 끝 날짜는 오늘까지입니다.');if(!Number.isFinite(value)||value<0||(provider==='naver'&&value>100)||(provider!=='naver'&&!Number.isSafeInteger(value)))throw Error('검색 지수는 0~100, 기사, 언급량은 0 이상의 정수로 입력하세요.');const expected=new URL(p.url).hostname;if(u.protocol!=='https:'||u.username||u.password||u.hostname!==expected)throw Error('선택한 사이트의 https 원문 주소를 입력하세요.');const next=[...records,{provider,keyword,value,start,end,scope,url:u.href,checkedAt:new Date().toISOString()}];localStorage.setItem(key,JSON.stringify(next));records=next;$('kind').value=provider;renderSource(provider);$('source-status').textContent='수치와 조회 조건을 저장했습니다. 원문 자동 검증은 수행하지 않았습니다.';}catch(err){$('source-status').textContent=err.message;}};
}
