import {cleanRecord,cohort,analyze,rate,nextActions,trendMatches} from './decision-model.mjs';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),today=()=>new Date(Date.now()+9*3600000).toISOString().slice(0,10),key='perjim-decisions-v18';let state={records:[],revisions:[],decisions:[]},demo=false,signature='',format='all',feed=null,feedError='';
try{const x=JSON.parse(localStorage.getItem(key)||'null');if(x&&Array.isArray(x.records)&&Array.isArray(x.revisions)&&Array.isArray(x.decisions)){state={...x,records:x.records.map(r=>cleanRecord(r,today()))};}}catch{}
const store=()=>localStorage.setItem(key,JSON.stringify(state));
const minus=n=>new Date(Date.parse(today()+'T00:00:00Z')-n*86400000).toISOString().slice(0,10);
function examples(){return Array.from({length:6},(_,i)=>cleanRecord({account:'https://example.com/photo-brand',url:`https://example.com/posts/${i+1}`,title:'예시'+' '+(i+1),topic:i<3?'풍경 사진':'동네 산책 사진',date:minus(17-i),format:'사진 피드',platform:'Instagram',basis:'reach',window:7,paid:'organic',exposures:i<3?1000:2000,shares:i<3?20:80,saves:i<3?30:100,follows:10,note:'기능 설명용 가상 통계, 실제 캠페인 성과 아님'},today()));}
const rows=()=>demo?examples():state.records;
export function decisionTrends(value){feed=value;feedError='';render();}
export function decisionTrendError(error){feedError=error;render();}
function putRecord(row){const index=state.records.findIndex(r=>r.id===row.id);if(index>=0){const fields=['account','url','title','topic','date','format','platform','basis','window','paid','exposures','shares','saves','follows','note'];if(fields.every(k=>state.records[index][k]===row[k]))return false;state.revisions.push({...state.records[index],replacedAt:new Date().toISOString()});state.records[index]=row;}else state.records.push(row);return true;}
function render(){
 const data=rows(),groups=[...new Set(data.map(cohort))];if(!groups.includes(signature))signature=groups[0]||'';
 $('decision-mode').textContent=demo?'예시 모드, 모든 콘텐츠 통계는 기능 설명용 가상 자료입니다. 현재 관심 자료는 실제 읽은 Google 자료로 별도 표시합니다.':`내 기록 ${data.length}개, ${state.revisions.length}개 이전 수치 보관, 주소만으로 비공개 통계를 자동 조회하지 않습니다.`;
 $('decision-demo').textContent=demo?'내 기록으로 돌아가기':'예시로 작동 방식 보기';
 $('decision-audit').textContent=`내 기록 ${state.records.length}개, 갱신 전 값 ${state.revisions.length}개, 저장한 다음 선택 ${state.decisions.length}개. 예시 자료는 저장하지 않습니다.`;
 if(!data.length){$('decision-analysis').innerHTML='<div class="panel"><h3>내 콘텐츠 자료가 아직 없습니다</h3><p>콘텐츠 통계를 등록하면 기준을 쌓습니다. 같은 조건에서 새 기록이 추가될 때 다음 판단이 달라집니다. 예시 버튼으로 비교 흐름을 먼저 확인할 수 있습니다.</p></div>';return;}
 const a=analyze(data,signature,format),group=data.filter(r=>cohort(r)===signature),r=group[0],formats=[...new Set(group.map(x=>x.format))],actions=nextActions(a),top=a.current.filter(x=>x.shares!==null).sort((x,y)=>y.shares/y.exposures-x.shares/x.exposures)[0],topic=top?.topic||a.current[0]?.topic||'',currentTrends=(feed?.items||[]).filter(x=>{const age=Date.now()-Date.parse(x.date);return age>=0&&age<=48*3600000;}),matches=trendMatches(topic,currentTrends),last=demo?null:state.decisions.filter(d=>d.signature===signature&&d.format===format).at(-1),newCount=last?a.group.filter(x=>x.registeredAt>last.at).length:null;
 const summary=`<section class="panel"><h2>내 반응은 어떻게 달라졌나요?</h2>${demo?'<p class="tag">예시 통계, 실제 성과 아님</p>':''}<div class="grid"><label>비교할 계정, 통계 조건<select id="decision-group">${groups.map(g=>{const x=data.find(r=>cohort(r)===g);return `<option value="${esc(g)}" ${g===signature?'selected':''}>${esc(x.account)}, ${esc(x.platform)}, ${x.basis==='reach'?'도달':'조회'}, ${x.window}일, ${x.paid==='organic'?'유료 없음':x.paid==='paid'?'유료 포함':'광고 미확인'}</option>`;}).join('')}</select></label><label>형식<select id="decision-filter-format"><option value="all">전체 형식, 구성 차이 함께 검토</option>${formats.map(f=>`<option ${f===format?'selected':''}>${esc(f)}</option>`).join('')}</select></label></div><p>최근 ${a.current.length}개 vs 이전 ${a.previous.length}개, 게시 날짜 순, 같은 계정, 플랫폼, 광고 여부, 통계 시점, 기준 수끼리 비교합니다.</p><p class="muted">%p는 비율의 차이입니다. 3% → 4%이면 +1%p입니다.</p><p class="muted">${r.paid==='unknown'?'실제 광고 기여가 미확인이라 노출 조건이 달랐을 수 있습니다. ':''}${a.small?'한쪽에 3개 미만이라 초기 관측으로만 봅니다.':'양쪽 3개는 운영 비교 기준이며 통계적 확신을 보장하지 않습니다.'} 전체 형식에서는 소재, 형식 구성이 다를 수 있습니다.</p>${newCount===null?'':`<p class="notice">지난 선택 저장 이후 ${newCount}개 기록이 추가 또는 갱신됐습니다. 기간별 반응과 이전 선택을 함께 검토하세요.</p>`}<div class="source-grid">${a.metrics.map(m=>{const max=Math.max(m.previous.value||0,m.current.value||0,0.01),value=v=>v===null?'자료 없음':v.toFixed(2)+'%',bar=(v,label)=>`<div class="comparison-row"><span>${label}</span><div class="comparison-track" aria-hidden="true"><i style="width:${v===null?0:v/max*100}%"></i></div><b>${value(v)}</b></div>`;return `<article class="source-tile"><h3>${m.label}</h3>${bar(m.previous.value,'이전')}${bar(m.current.value,'최근')}<p class="metric-delta">${m.delta===null?'변화 계산 불가':(m.delta>0?'+':'')+m.delta.toFixed(2)+'%p'}</p><details><summary>계산 근거 보기</summary><p>이전 ${m.previous.n}/${m.previous.d}, 통계 있는 글 ${m.previous.coverage}/${m.previous.total}개<br>최근 ${m.current.n}/${m.current.d}, 통계 있는 글 ${m.current.coverage}/${m.current.total}개</p><p>빈값은 제외합니다. 막대 길이는 이 지표의 두 기간을 상대 비교합니다. 전체 사람의 비율이나 실제 공유한 고유 사람 수가 아닙니다.</p></details></article>`;}).join('')}</div></section>`;
 const choices=`<section class="panel"><h2>다음 콘텐츠 선택</h2><p>관측한 변화에 따른 시험 제안입니다. 원인을 확정하지 않고 한 요소씩 바꿔 다음 통계에서 확인하세요.</p><div class="source-grid">${actions.map((x,i)=>`<article class="source-tile"><span class="tag">${demo?'예시 판단':'내 통계에 따른 가설'}</span><h3>${esc(x.title)}</h3><p>${esc(x.evidence)}</p><p>${esc(x.action)}</p><button data-save-decision="${i}" ${demo?'disabled':''}>${demo?'예시는 실제 선택으로 저장하지 않음':'이번에 시험할 안으로 저장'}</button></article>`).join('')}</div><p id="decision-choice-status" role="status"></p></section>`;
 const signals=`<section class="panel"><h3>내 소재에 연결할 현재 관심</h3><p>검토할 내 소재: <b>${esc(topic||'소재 미확인')}</b>${top?', 최근 공유 반응이 높은 콘텐츠의 소재':''}</p><p class="muted">검색 키워드의 단어 연관성으로 찾은 후보입니다. 내 반응이 검색 관심 때문에 달라졌다는 분석은 아닙니다. ${feedError?'최신 자료 확인 실패, '+esc(feedError)+', ':''}${feed?'최근 48시간 관심, 자료 확인 '+new Date(feed.fetchedAt).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'}):(feedError?'현재 검색 자료 없음':'최신 검색 자료를 읽는 중입니다.')}</p>${matches.length?matches.map(x=>`<article class="diagnostic"><h4>${esc(x.title)}</h4><p>Google 피드 검색량 표시 ${esc(x.traffic)}, 발생 ${new Date(x.date).toLocaleString('ko-KR')}</p><p>내 직접 경험과 연결되면 같은 콘텐츠 형식에서 소재만 바꿔 시험해 보세요.</p><details><summary>뉴스와 출처 보기</summary>${x.news.map(n=>`<p><a href="${esc(n.url)}" target="_blank" rel="noopener">${esc(n.title)}</a></p>`).join('')}<a href="https://trends.google.com/trending?geo=KR" target="_blank" rel="noopener">Google Trends 원문</a></details><button data-decision-trend="${esc(x.title)}">이 소재의 제작 방향 검토</button></article>`).join(''):`<p>${feed?'지금 읽은 자료에서 직접 연결할 후보를 찾지 못했습니다.':'관심 자료 확인 전에는 후보를 제안하지 않습니다.'} 무관한 유행을 억지로 추천하지 않습니다. 오늘, 이번 주 키워드에서 다른 출처도 확인하세요.</p>`}</section>`;
 const table=`<details class="panel"><summary>비교한 콘텐츠와 이전 선택 보기</summary><div class="table-wrap"><table><caption>최근과 이전 비교에 포함한 콘텐츠, 최대 6개</caption><thead><tr><th>기간</th><th>콘텐츠</th><th>기준 수</th><th>공유</th><th>저장</th><th>게시물 팔로우</th></tr></thead><tbody>${[...a.current,...a.previous].map((x,i)=>`<tr><td>${i<a.current.length?'최근':'이전'}</td><td>${esc(x.title)}<br>${esc(x.topic)}, ${x.date}<details><summary>메모, 원문</summary><p>${esc(x.note||'메모 없음')}</p>${demo?'예시 주소, 실제 콘텐츠 없음':`<a href="${esc(x.url)}" target="_blank" rel="noopener">게시물 원문</a>`}</details></td><td>${x.exposures.toLocaleString()}</td><td>${x.shares??'미확인'}</td><td>${x.saves??'미확인'}</td><td>${x.follows??'미확인'}</td></tr>`).join('')}</tbody></table></div>${demo?'':state.decisions.filter(d=>d.signature===signature).slice(-5).reverse().map(d=>`<article class="diagnostic"><h4>${esc(d.title)}</h4><p>${esc(d.evidence)}</p><p>${esc(d.action)}</p><small>${new Date(d.at).toLocaleString('ko-KR')}, 당시 자료 ${d.rowIds.length}개</small></article>`).join('')}</details>`;
 $('decision-analysis').innerHTML=summary+choices+signals+table;
 $('decision-group').onchange=e=>{signature=e.target.value;format='all';render();};$('decision-filter-format').onchange=e=>{format=e.target.value;render();};
 $('decision-analysis').onclick=e=>{const b=e.target.closest('[data-save-decision]'),trend=e.target.closest('[data-decision-trend]');if(trend){window.dispatchEvent(new CustomEvent('decision-trend',{detail:{topic,platform:a.current[0]?.platform,title:trend.dataset.decisionTrend}}));return;}if(!b||demo)return;try{const action=actions[Number(b.dataset.saveDecision)],record={...action,at:new Date().toISOString(),signature,format,rowIds:[...a.current,...a.previous].map(x=>x.id),metrics:a.metrics.map(m=>({key:m.key,previous:m.previous,current:m.current,delta:m.delta})),trendCandidates:matches.map(x=>({title:x.title,traffic:x.traffic,date:x.date})),trendCheckedAt:feed?.fetchedAt||null};state.decisions.push(record);try{store();}catch(err){state.decisions.pop();throw err;}render();$('decision-choice-status').textContent='이번 선택과 당시 통계를 저장했습니다. 다음 기록을 추가하면 변화와 함께 검토할 수 있습니다.';}catch(err){$('decision-choice-status').textContent=err.message;}};
}
export function setupDecision(){
 $('decision-add').onclick=()=>{$('decision-entry').open=true;$('decision-url').focus();};$('decision-demo').onclick=()=>{demo=!demo;signature='';format='all';render();};
 const latest=state.records.at(-1);if(latest)for(const k of ['account','platform','window','paid','basis'])$('decision-'+k).value=latest[k];$('decision-date').value=minus(Number($('decision-window').value));$('decision-form').onsubmit=e=>{e.preventDefault();try{const value=name=>$('decision-'+name).value.trim(),r=cleanRecord(Object.fromEntries(['account','url','title','topic','date','format','platform','window','paid','basis','exposures','shares','saves','follows','note'].map(k=>[k,value(k)])),today());r.registeredAt=new Date().toISOString();const before=JSON.stringify(state);const changed=putRecord(r);try{store();}catch(err){state=JSON.parse(before);throw err;}demo=false;signature=cohort(r);format='all';render();$('decision-status').textContent='통계를 저장했습니다. 같은 조건의 비교와 다음 선택을 갱신했습니다.';$('decision-entry').open=false;$('decision-mode').textContent+=changed?', 새 통계 저장 완료':', 이전 기록과 같아 그대로 유지';$('decision-analysis').scrollIntoView({block:'start',behavior:'smooth'});}catch(err){$('decision-status').textContent=err.message;}};
 $('decision-export').onclick=()=>{const u=URL.createObjectURL(new Blob([JSON.stringify({kind:'perjim-decisions',version:1,...state},null,2)],{type:'application/json'})),a=document.createElement('a');a.href=u;a.download='퍼짐-콘텐츠기록-'+today()+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);$('decision-backup-status').textContent='내 실제 입력 기록의 다운로드를 요청했습니다. 브라우저 다운로드 상태를 확인하세요.';};
 $('decision-import').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>2000000)throw Error('2MB 이하 기록 파일을 선택하세요.');const incoming=JSON.parse(await file.text());if(incoming.kind!=='perjim-decisions'||incoming.version!==1||!Array.isArray(incoming.records)||incoming.records.length>2000)throw Error('퍼짐에서 내려받은 콘텐츠 기록 파일을 선택하세요.');const records=incoming.records.map(r=>({...cleanRecord(r,today()),registeredAt:new Date().toISOString()})),ids=new Set();for(const r of records){if(ids.has(r.id))throw Error('파일에 중복 콘텐츠가 있습니다.');ids.add(r.id);}const before=JSON.stringify(state);for(const r of records)putRecord(r);try{store();}catch(err){state=JSON.parse(before);throw err;}demo=false;render();$('decision-backup-status').textContent=`${records.length}개 콘텐츠를 병합했습니다. 현재 기획 선택 이력은 유지합니다. 가져온 파일의 선택 이력은 자동 병합하지 않습니다.`;}catch(err){$('decision-backup-status').textContent=err.message;}};render();
}
