import {deliveryReview,guidanceSources} from './recommendation-guidance.mjs';
import {setupDecision,decisionTrends,decisionTrendError} from './decision-ui.js?v=19';
import {setupWorkflow,brandContext,trendContext} from './brand-workflow.js';
import {renderSource,setupSources} from './trend-sources.js';
import {setupTrendEvidence} from './trend-evidence-ui.js';
import {renderBlack,setupResearch} from './keyword-research.js';
import {subject,diagnoseAccount,publicEvidence,nextContent} from './diagnosis.mjs';
import {recommend} from './strategy.mjs';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safeURL=s=>{try{const u=new URL(s);return ['https:','http:'].includes(u.protocol)&&!u.username&&!u.password?u.href:'';}catch{return '';}};
const link=(url,title)=>safeURL(url)?`<a href="${esc(safeURL(url))}" target="_blank" rel="noopener">${esc(title)}</a>`:esc(title);
const date=s=>new Date(s).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'});
let account=null,feed=null,selected=null,analysis=null,accounts=[],renderedTrends=[],social=[];try{social=JSON.parse(localStorage.getItem('cpl-guide-v08-social')||'[]');if(!Array.isArray(social))social=[];}catch{}
async function api(path,body){const r=await fetch(path,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{});const data=await r.json();if(!r.ok)throw Error(data.error||'자료를 읽지 못했습니다.');return data;}
function suggestions(){if(!account)return;analysis=recommend(account,subject(account,$('topic').value).text,'공유와 새 독자 발견');$('recommendations').innerHTML=accounts.map(a=>{const t=subject(a,$('topic').value),checks=diagnoseAccount(a),next=nextContent(a,t.text),review=deliveryReview(next);return `<article class="recommendation"><span class="tag">${esc(a.platform)}</span><h2>보완할 요소</h2><p class="source">${esc(t.text)}. ${esc(t.basis)}</p>${checks.map(c=>`<div class="diagnostic"><span class="priority">${esc(c.level)}</span><h3>${esc(c.title)}</h3><p class="evidence">${esc(c.fact)}</p><p>${esc(c.action)}</p></div>`).join('')}<h2>다음 콘텐츠 추천</h2><p class="source">${esc(next.basis)}</p><h3>${esc(next.title)}</h3><p>${esc(next.outline)}</p><p>참여 질문: ${esc(next.question)}</p><p><b>선택 이유</b><br>${esc(next.reason)}</p><p class="source">${esc(next.limit)}</p>${next.candidates.length?`<details><summary>두 콘텐츠 안 비교</summary>${next.candidates.map(c=>`<article class="diagnostic"><h3>${esc(c.id)}안: ${esc(c.title)}</h3><p>${esc(c.outline)}</p><p>근거: ${esc(c.basis)}</p><p>검증: ${esc(c.check)}</p></article>`).join('')}</details>`:''}${next.evidence.length?`<details><summary>판단에 사용한 글 ${next.evidence.length}개 보기</summary>${next.evidence.map(p=>`<p>${link(p.url,p.title)}</p><p class="source">${esc(p.excerpt)}</p>`).join('')}</details>`:''}${review.items.length?`<details><summary>만들기 전 확인할 네 가지</summary><p class="source">${esc(review.intro)}</p>${review.items.map(i=>`<article class="diagnostic"><h3>${esc(i.title)}</h3><p><b>${esc(i.draft)}</b></p><p>${esc(i.action)}</p><p>확인 후 바꿀 점: ${esc(i.check)}</p><details><summary>참고한 원문</summary><p>${link(guidanceSources[i.source].url,guidanceSources[i.source].title)}</p><p class="source">발행 ${esc(guidanceSources[i.source].date)} / 확인 2026-10-08. SNS 성과를 입증한 자료는 아닙니다.</p></details></article>`).join('')}</details>`:''}<button data-next-account="${esc(a.url)}">이 방향으로 콘텐츠 구성하기</button></article>`;}).join('');$('conditions').hidden=false;brandContext(subject(account,$('topic').value).text,account.platform);}
$('account-form').onsubmit=async e=>{e.preventDefault();const urls=[...new Set($('url').value.split(/[\n,]+/).map(x=>x.trim()).filter(Boolean))];if(!urls.length||urls.length>5){$('account-status').textContent='주소를 한 줄에 하나씩 최대 5개 넣어 주세요.';return;}$('analyze').disabled=true;accounts=[];account=null;$('conditions').hidden=true;$('account-result').innerHTML='';selected=null;$('direction').innerHTML='';const errors=[];try{for(const url of urls){$('account-status').textContent=`${accounts.length+errors.length+1}/${urls.length}개 공개 주소 확인 중…`;try{accounts.push(await api('/api/account',{url}));}catch(error){errors.push(url+': '+error.message);}}if(!accounts.length){$('account-status').textContent=errors.join(' / ');return;}account=accounts[0];$('account-status').textContent=`${accounts.length}개 주소를 등록했습니다. 확인된 자료를 바탕으로 방향을 제안합니다. 읽지 못한 정보는 확인하지 못함으로 표시합니다.`+(errors.length?' 확인 실패: '+errors.join(' / '):'');$('account-result').innerHTML=accounts.map(a=>`<article class="panel"><h2>${esc(a.platform)} 공개 자료 확인</h2><p class="source">확인 시점 ${date(a.checkedAt)}</p><dl class="public-evidence">${publicEvidence(a).map(x=>`<div><dt>${esc(x.label)}</dt><dd>${esc(x.value)}</dd></div>`).join('')}</dl><details><summary>읽은 자료와 출처 보기</summary><p>${link(a.url,'계정 원문')}</p><p>${esc(a.limitation)}</p>${a.reason?`<p>접근 결과: ${esc(a.reason)}</p>`:''}${a.posts.length?`<ul class="read-posts">${a.posts.map(p=>`<li>${link(p.url,p.title)}<p>${esc(p.description||'본문 확인하지 못함')}</p><small>${esc(p.date||'게시 날짜 확인하지 못함')}</small></li>`).join('')}</ul>`:''}</details></article>`).join('');suggestions();}finally{$('analyze').disabled=false;}};
$('topic').addEventListener('change',suggestions);
$('recommendations').onclick=e=>{const b=e.target.closest('[data-next-account]');if(!b)return;const a=accounts.find(x=>x.url===b.dataset.nextAccount);if(a){brandContext(subject(a,$('topic').value).text,a.platform,nextContent(a,subject(a,$('topic').value).text));setTab('workflow');}};
function setTab(which){for(const name of ['decision','diagnosis','keywords','workflow']){$(name==='keywords'?'keyword-view':name+'-view').hidden=name!==which;$('tab-'+name).setAttribute('aria-selected',String(name===which));$('tab-'+name).tabIndex=name===which?0:-1;}if(which==='keywords')renderTrends();}
const tabNames=['diagnosis','keywords','workflow','decision'];for(const which of tabNames){$('tab-'+which).onclick=()=>setTab(which);$('tab-'+which).onkeydown=e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const next=e.key==='Home'?tabNames[0]:e.key==='End'?tabNames.at(-1):tabNames[(tabNames.indexOf(which)+(e.key==='ArrowLeft'?3:1))%4];setTab(next);$('tab-'+next).focus();}};}
async function refresh(){$('refresh').disabled=true;$('trend-status').textContent='한국 검색 관심 자료를 확인하고 있습니다…';try{feed=await api('/api/trends');decisionTrends(feed);renderTrends();}catch(error){decisionTrendError(error.message);$('trend-status').textContent='최신 자료 확인 실패: '+error.message+(feed?' 이전에 읽은 자료를 유지합니다. 새 자료로 표시하지 않습니다.':'');}finally{$('refresh').disabled=false;}}
function renderTrends(){const kind=$('kind').value,period=$('period').value==='today'?24:168,keyword=$('keyword').value.trim().toLowerCase();
 if(kind==='black'){renderBlack();return;}
 if(['naver','bigkinds','some','words'].includes(kind)){renderSource(kind);return;}
 if(kind==='social'){const now=Date.now(),filtered=social.filter(x=>{const age=(now-Date.parse(x.after))/3600000;return age>=0&&age<=period&&(!keyword||x.title.toLowerCase().includes(keyword));}).sort((a,b)=>Date.parse(b.after)-Date.parse(a.after));$('trend-status').textContent=`사용자 등록 확산 관측 ${filtered.length}건, 두 시점의 수치 증가 기록입니다. 원본 대조와 광고 기여 확인은 미완료입니다.`;$('trend-list').innerHTML=filtered.length?filtered.map(x=>`<article class="panel trend-card"><span class="tag">${esc(x.metric)} 증가, 사용자 관측</span><h3>${esc(x.title)}</h3><p class="stat">${x.beforeValue.toLocaleString()} → ${x.afterValue.toLocaleString()}</p><p>${date(x.before)} → ${date(x.after)}</p><p>${link(x.url,'원본 콘텐츠')}, ${link(x.evidence,'관측 근거')}</p><p class="muted">인기 전체 순위나 자연 확산 여부는 확인하지 못했습니다.</p></article>`).join(''):'<article class="panel"><h3>현재 조건의 확산 관측 기록이 없습니다</h3><p>검색 관심 신호로 소재를 탐색하거나 아래에서 실제 두 시점의 관측 기록을 등록하세요. 예전 성공 사례를 현재 바이럴로 표시하지 않습니다.</p></article>';return;}
 if(!feed){$('trend-list').innerHTML='';return;}const week=$('period').value==='week',day=t=>new Date(Date.parse(t)+9*3600000).toISOString().slice(0,10),traffic=t=>{const n=parseFloat(String(t).replace(/,/g,''))||0;return n*(/M/i.test(t)?1000000:/K/i.test(t)?1000:1);};const sourceRows=week?(feed.history?.days||[]).flatMap(d=>d.items.map(x=>({...x,observedDay:d.day}))):feed.items.filter(x=>day(x.date)===(feed.history?.today||day(new Date().toISOString())));const merged=new Map();for(const x of sourceRows){const old=merged.get(x.title);if(!old)merged.set(x.title,{...x,observedDays:new Set(x.observedDay?[x.observedDay]:[])});else{old.observedDays.add(x.observedDay);if(traffic(x.traffic)>traffic(old.traffic)){old.traffic=x.traffic;old.news=x.news;}}}const items=[...merged.values()].filter(x=>!keyword||(x.title+' '+x.news.map(n=>n.title).join(' ')).toLowerCase().includes(keyword)).sort((a,b)=>week?b.observedDays.size-a.observedDays.size||traffic(b.traffic)-traffic(a.traffic):traffic(b.traffic)-traffic(a.traffic));$('trend-status').textContent=`${week?'이번 주':'오늘'} 키워드 ${items.length}건, 수집 ${date(feed.fetchedAt)}, ${week?'실제 수집 '+(feed.history?.days.length||0)+'일. 수집 시작 이전 날짜는 자료 없음. 관측 일수 → 최고 검색량 표시 순으로 정렬.':'피드 검색량 표시가 큰 순으로 정렬.'} 검색 관심이며 SNS 바이럴, 브랜드평판 점수는 아닙니다.`;
renderedTrends=items;$('trend-list').innerHTML=items.length?items.map((x,i)=>`<article class="panel trend-card"><span class="tag">검색 관심 신호, SNS 반응 미확인</span><h3>${esc(x.title)}</h3><dl class="trend-metrics"><div><dt>${week?'최고 검색량 표시':'검색량 표시'}</dt><dd>${esc(x.traffic||'미제공')}</dd></div><div><dt>${week?'이번 주 관측':'오늘 관측'}</dt><dd>${week?x.observedDays.size:1}일</dd></div><div><dt>연결 기사</dt><dd>${x.news.length}건</dd></div></dl><p class="source">검색량은 피드 제공값, 고유 사용자 수 아님<br>기사 건수는 이 카드에 연결된 기사만 집계<br>발생 시점 ${date(x.date)}</p><details class="evidence-details"><summary>근거 보기, 뉴스와 출처</summary>${x.news.map(n=>`<p>${link(n.url,n.title)}<br><small>${esc(n.publisher)}</small></p>`).join('')}<p>${link(feed.source,'Google Trends 출처')}</p><p class="muted">비교 가능한 이전 검색량이 없어 증가율은 계산하지 않았습니다.</p></details><button data-trend="${i}">내 브랜드와 연결 검토</button></article>`).join(''):'<article class="panel"><h3>이 조건에 맞는 관심 신호가 없습니다</h3><p>키워드를 바꾸거나 기간을 넓혀 주세요. 관련 없는 유행을 억지로 연결하지 않습니다.</p></article>';}
$('trend-list').addEventListener('click',e=>{const b=e.target.closest('[data-trend]');if(!b)return;const x=renderedTrends[Number(b.dataset.trend)];if(!x)return;selected=x;trendContext(x.title,`Google Trends 피드 검색량 표시 ${x.traffic||'미제공'}, 발생 ${date(x.date)}, 조회 ${date(feed.fetchedAt)}. SNS 반응은 미확인.`,feed.source);setTab('workflow');});
$('refresh').onclick=refresh;for(const id of ['period','keyword','kind'])$(id).addEventListener('input',renderTrends);
$('social-form').onsubmit=e=>{e.preventDefault();try{const before=new Date($('social-before').value),after=new Date($('social-after').value),beforeValue=Number($('social-old').value),afterValue=Number($('social-new').value);if(!Number.isFinite(+before)||!Number.isFinite(+after)||after<=before||+after>Date.now())throw Error('현재 관측은 이전 시점 이후이고 지금 이전이어야 합니다.');if(!Number.isSafeInteger(beforeValue)||!Number.isSafeInteger(afterValue)||beforeValue<0||afterValue<=beforeValue)throw Error('현재 수치가 이전보다 증가한 정수 기록을 넣어 주세요.');const url=safeURL($('social-url').value),evidence=safeURL($('social-evidence').value);if(!url||!evidence)throw Error('원본과 근거 주소를 확인해 주세요.');const next=[...social,{title:$('social-title').value.trim(),url,evidence,before:before.toISOString(),after:after.toISOString(),beforeValue,afterValue,metric:$('social-metric').value}];localStorage.setItem('cpl-guide-v08-social',JSON.stringify(next));social=next;$('kind').value='social';$('social-status').textContent='관측 기록을 저장했습니다. 실제 출처 대조와 광고 여부 검토는 별도입니다.';renderTrends();}catch(error){$('social-status').textContent=error.message;}};
$('download').onclick=()=>{const data={createdAt:new Date().toISOString(),account,accounts,topic:$('topic').value,goal:$('goal').value,recommendations:analysis,selectedTrend:selected,trendSource:feed?{url:feed.source,fetchedAt:feed.fetchedAt}:null,limitations:['추천은 공개 정보와 입력 주제에 따른 규칙 기반 제안입니다.','검색량은 SNS 바이럴 수치가 아닙니다.','비공개 반응과 브랜드 기억, 재방문은 확인하지 못했습니다.']},u=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=u;a.download='퍼짐-SNS-진단-'+Date.now()+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);};
setupResearch();
setupSources();
setupTrendEvidence();
setupWorkflow();
setupDecision();
window.addEventListener('decision-trend',e=>{brandContext(e.detail.topic,e.detail.platform||'Instagram');trendContext(e.detail.title,'내 소재와 단어가 연결된 현재 관심 후보입니다. 실제 브랜드 적합성을 검토하세요.','https://trends.google.com/trending?geo=KR');setTab('workflow');});
window.addEventListener('trend-evidence-use',e=>{brandContext($('topic').value.trim()||'내 브랜드','기타 SNS');trendContext(e.detail.keyword,e.detail.summary,e.detail.source);setTab('workflow');});
refresh();
