const themes=[
 {id:'place',label:'장소와 계절',pattern:/산책|동네|전시|공원|풍경|여행|계절|단풍|색감/,title:'한 장소를 다른 시간에 다시 보기',outline:'읽은 글의 장소 한 곳을 다시 찾아 두 시간대의 차이를 보여주세요. 직접 확인한 변화와 방문 조건을 적고 이전 글을 연결하세요.',question:'같은 장소에서 다시 보고 싶은 장면은 무엇인가요?',alternative:'처음 가는 사람을 위한 장소 안내',altOutline:'직접 확인한 위치, 방문 조건과 준비할 내용을 묶어 다시 꺼내 볼 수 있는 글로 구성하세요.',reason:'장소에 대한 직접 관찰을 이어갈 수 있습니다. 반복되는 소재가 있는지 공개 글에서 확인한 뒤 고른 안입니다.',altReason:'방문 조건을 실제로 확인해야 하므로 추가 취재가 필요합니다. 정보를 모으기만 하면 계정의 관점이 약해질 수 있습니다.'},
 {id:'money',label:'생활 속 소비',pattern:/생활비|가격|비용|물가|절약|소비|지출|가계부|장보기|구독/,title:'같은 생활 상황에서 달라진 선택',outline:'공개 글에서 다룬 소비 상황 하나를 골라 비용, 편의와 만족을 같은 기준으로 비교하세요. 실제 지출을 확인한 범위와 개인 경험을 구분하세요.',question:'비용과 편의 중 무엇을 우선하셨나요?',alternative:'따라 할 수 있는 소비 점검표',altOutline:'확인한 경험에서 다른 사람이 적용할 조건을 추리고 짧은 점검표로 만드세요. 모든 사람에게 같은 선택을 권하지 마세요.',reason:'기존 소재에 본인의 선택 이유를 더할 수 있습니다. 숫자를 확인하지 못했다면 비용 효과는 주장하지 않습니다.',altReason:'저장할 이유는 분명하지만 적용 조건을 추가로 확인해야 합니다. 절약 효과를 보장하는 문구는 피하세요.'},
 {id:'experience',label:'직접 해본 경험',pattern:/후기|리뷰|경험|사용|먹어|맛|요리|실험|읽은|독서/,title:'직접 해본 뒤 생각이 바뀐 한 가지',outline:'읽은 글의 경험 하나를 골라 예상, 실제 장면과 달라진 생각을 보여주세요. 브랜드의 관점이 드러나는 문장을 마지막에 남기세요.',question:'비슷한 경험에서 예상과 달랐던 점이 있으신가요?',alternative:'처음 해보는 사람에게 알려줄 조건',altOutline:'실제 경험에서 좋았던 점과 맞지 않았던 조건을 함께 정리하세요. 누구에게 유용한지 먼저 밝히세요.',reason:'이미 다룬 경험에 새 관점을 더할 수 있습니다. 감탄만 반복하지 않고 구체적인 장면을 남기는 안입니다.',altReason:'독자의 상황을 추가로 확인해야 합니다. 개인 경험을 보편적인 평가로 확대하지 마세요.'}
];
export function contentDecision(account,topic,now=new Date()){
 const seen=new Set(),posts=(account.posts||[]).filter(p=>{if(!p.title?.trim())return false;const d=Date.parse(p.date);if(Number.isFinite(d)&&d>+now)return false;const key=p.url||p.title;if(seen.has(key))return false;seen.add(key);return true;});
 if(!posts.length)return {kind:'insufficient',basis:'개별 게시물을 확인하지 못함. 주제에 따른 시작용 제안이며 현재 계정의 약점이나 효과를 평가하지 않았습니다.',title:topic&&topic!=='내 브랜드'?`${topic}: 나의 관점`:'이 계정에서 앞으로 전할 이야기',outline:'대표 경험 하나와 이 계정에서 계속 다룰 관점을 소개하세요. 공개 콘텐츠가 확인되면 대안 비교를 추가합니다.',question:'다음에 어떤 이야기를 보고 싶으신가요?',evidence:[],candidates:[],reason:'비교할 콘텐츠 자료가 없어 특정 안의 우위를 판단하지 않습니다.',limit:'이미지, 실제 독자 반응과 공유 효과는 확인하지 못함.'};
 const counts=themes.map(t=>({...t,rows:posts.filter(p=>t.pattern.test(p.title+' '+(p.description||'')))})).filter(t=>t.rows.length).sort((a,b)=>b.rows.length-a.rows.length),theme=counts[0];
 if(!theme)return {kind:'needs-context',basis:`중복과 미래 날짜를 제외한 공개 글 ${posts.length}개를 검토했습니다. 정해진 소재 분류로 공통 주제를 찾지 못했습니다.`,title:'최근 글에서 독자가 답할 수 있는 질문 하나 고르기',outline:'아래 읽은 글의 제목과 본문 일부를 확인하고 같은 독자 상황을 다루는 글 두 개를 고르세요. 소재를 확인하기 전에는 후속 콘텐츠의 우위를 정하지 않습니다.',question:'이 글에서 더 알고 싶은 부분은 무엇인가요?',evidence:posts.slice(0,3).map(p=>({title:p.title,url:p.url,excerpt:(p.description||'본문 확인하지 못함').slice(0,160)})),candidates:[],reason:'새 분류나 독자 맥락 확인이 필요합니다. 길이가 짧다는 이유만으로 제목을 실패로 판단하지 않습니다.',limit:'정해진 단어 분류에 포함되지 않는 콘텐츠가 있습니다. 본문 전체와 실제 반응은 확인하지 못함.'};
 const evidence=theme.rows.slice(0,3).map(p=>({title:p.title,url:p.url,excerpt:(p.description||'본문 확인하지 못함').slice(0,160)}));
 const candidates=[{id:'A',title:theme.title,outline:theme.outline,basis:theme.reason,check:'독자가 파악한 계정의 관점과 구체적인 경험을 확인합니다.'},{id:'B',title:theme.alternative,outline:theme.altOutline,basis:theme.altReason,check:'독자가 실제로 사용할 조건을 찾는지 확인합니다.'}];
 const utility=theme.rows.filter(p=>/방법|점검표|준비물|체크리스트|가이드|안내|정리/.test(p.title+' '+(p.description||''))).length;
 const selected=utility>=2&&utility>theme.rows.length/2?'B':'A',chosen=candidates.find(c=>c.id===selected);
 const anchor=theme.rows[0].title;
 candidates.forEach(c=>{c.outline=`기준 글: "${anchor}". ${c.outline}`;});
 return {kind:'observed',selected,basis:`읽은 공개 글 ${posts.length}개 중 ${theme.rows.length}개에서 "${theme.label}" 관련 표현을 찾았습니다. 글 전체나 반응 순위가 아니라 제목과 공개 본문 일부의 단어 분류입니다.`,title:chosen.title,outline:chosen.outline,question:theme.question,evidence,candidates,reason:`${selected}안을 우선 제안합니다. ${selected==='B'?`관련 글 ${theme.rows.length}개 중 ${utility}개에 안내나 정리 표현이 있어 기존 정보 제공 방식을 이어갑니다.`:`${theme.rows.length>1?'같은 소재를 다룬 글이 여러 개 있어':'표본이 한 개라 반복 소재로 확정하지 않고'} 기준 글의 경험과 계정의 관점을 이어가는 안을 검토합니다.`} 분류가 실제 글과 맞는지 아래 근거를 확인하세요. 안내 표현의 개수는 독자가 좋아했다는 증거가 아닙니다.`,limit:'자료와의 연결성을 기준으로 선택했습니다. 성과 우위, 독자 반응, 브랜드 기억과 재방문은 확인하지 못함.'};
}
